# Generated by Django 5.1.7 on 2025-03-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id_time_slot', models.AutoField(primary_key=True, serialize=False)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('slot_type', models.CharField(choices=[('regular', 'Regular'), ('special', 'Special')], max_length=10)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('id_time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_slot', to='location.timeslot')),
            ],
        ),
    ]
