# Generated by Django 5.1.7 on 2025-03-19 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('review', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('no_show', 'No Show'), ('confirmed', 'Confirmed'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_by_admin', 'Cancelled by Admin'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='location.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTimeSlot',
            fields=[
                ('id_booking_time_slot', models.AutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='booking.booking')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='location.timeslot')),
            ],
        ),
    ]
